"""empty message

Revision ID: 2a922c2d4cd
Revises: None
Create Date: 2017-06-02 08:06:09.811943

"""

# revision identifiers, used by Alembic.
revision = '2a922c2d4cd'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.types import Text

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('site_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('received', sa.DateTime(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_site_id'), 'messages', ['site_id'], unique=False)
    op.create_index(op.f('ix_messages_ts'), 'messages', ['ts'], unique=False)
    op.create_index('message_content', 'messages', ['message'], unique=False, postgresql_using='gin')
    op.create_index('message_type', 'messages', [sa.text(u"(messages.message -> 'type')")], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('message_type', table_name='messages')
    op.drop_index('message_content', table_name='messages')
    op.drop_index(op.f('ix_messages_ts'), table_name='messages')
    op.drop_index(op.f('ix_messages_site_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('sites')
    ### end Alembic commands ###
