"""empty message

Revision ID: 3f16bf4dbd75
Revises: None
Create Date: 2017-06-01 11:24:01.992440

"""

# revision identifiers, used by Alembic.
revision = '3f16bf4dbd75'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
